#!/bin/bash

if [ $# != 1 ]
then
    echo "$0 <base-file-name>"
    exit -1
fi

if [[ "$1" == *".cpp" || "$1" == *".h" ]]
then
    echo "Specify file name without extention"
    exit -1
fi

rm ./back_end_src/${1}.h
rm ./back_end_src/${1}.cpp
